In [142]:
import pandas as pd  
import numpy as np  
from sklearn.naive_bayes import GaussianNB as NaiveBayes
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing
from sklearn.model_selection import train_test_split 
import matplotlib.pyplot as plt  
%matplotlib inline

In [143]:
dataset = pd.read_csv("MobileData.csv")

In [144]:
dataset.shape

(2000, 21)

In [145]:
dataset.head()


battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores     ...       px_height  px_width   ram  sc_h  sc_w  \
0        188        2     ...              20       756  2549     9     7   
1        136        3     ...             905      1988  2631    17     3   
2        145        5     ...            1263      1716  2603    11     2   
3        131        6     ...            1216      1786  2769    16     8   
4        141        2     ...            1208      1212  1411     8     2   

   talk_time  three_g  touch_screen  wifi  price_range  
0         19        0             0     1            1  
1          7        1             1     0            2  
2          9        1             1     0            2  
3         11        1             0     0            2  
4         15        1             1     0            1  

[5 rows x 21 columns]

In [146]:
X = dataset.drop('price_range', axis=1) 
X=X.apply(lambda x: (x - np.mean(x)) / (np.max(x) - np.min(x)))
print(X.head())
y = dataset['price_range']  


   battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2   2         20       756  2549     9     7         19   
1        136        3   6        905      1988  2631    17     3          7   
2        145        5   6       1263      1716  2603    11     2          9   
3        131        6   9       1216      1786  2769    16     8         11   
4        141        2  14       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  
0        0 

In [147]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20) 

In [148]:

classifier = DecisionTreeClassifier() 
bayes_classifier = NaiveBayes()
knn_classifier = KNN(n_neighbors = 5)

classifier.fit(X_train, y_train)  
bayes_classifier.fit(X_train,y_train)
knn_classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [149]:
y_pred = classifier.predict(X_test) 
# Predictions using knn
pred_Y_KNN = knn_classifier.predict(X_test)
# Predictions using Bayes
pred_Y_Bayes = bayes_classifier.predict(X_test)

In [150]:
from sklearn.metrics import classification_report, confusion_matrix  
print ("Confusion Matrix  - Decision Tree:")
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))
print ("Confusion Matrix  - KNN:")
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))
print ("Confusion Matrix  - Naive Bayes:")
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

Confusion Matrix  - Decision Tree:
[[96 10  0  0]
 [16 73  7  0]
 [ 0 16 67 17]
 [ 0  0 13 85]]
             precision    recall  f1-score   support

          0       0.86      0.91      0.88       106
          1       0.74      0.76      0.75        96
          2       0.77      0.67      0.72       100
          3       0.83      0.87      0.85        98

avg / total       0.80      0.80      0.80       400

Confusion Matrix  - KNN:
[[96 10  0  0]
 [16 73  7  0]
 [ 0 16 67 17]
 [ 0  0 13 85]]
             precision    recall  f1-score   support

          0       0.86      0.91      0.88       106
          1       0.74      0.76      0.75        96
          2       0.77      0.67      0.72       100
          3       0.83      0.87      0.85        98

avg / total       0.80      0.80      0.80       400

Confusion Matrix  - Naive Bayes:
[[96 10  0  0]
 [16 73  7  0]
 [ 0 16 67 17]
 [ 0  0 13 85]]
             precision    recall  f1-score   support

          0       0.86      

In [151]:
print ("Accuracy:")
print ("Decision Tree:",accuracy_score(y_pred,y_test))
print ("KNN:",accuracy_score(y_pred,y_test))
print ("Naive Bayes:",accuracy_score(y_pred,y_test))

print ("Precision:")
print ("Decision Tree:",precision_score(y_pred,y_test,average="micro"))
print ("KNN:",accuracy_score(y_pred,y_test))
print ("Naive Bayes:",precision_score(y_pred,y_test,average="micro"))

print ("Recall:")
print ("Decision Tree:",recall_score(y_pred,y_test,average="micro"))
print ("KNN:",accuracy_score(y_pred,y_test))
print ("Naive Bayes:",recall_score(y_pred,y_test,average="micro"))

Accuracy:
('Decision Tree:', 0.8025)
('KNN:', 0.8025)
('Naive Bayes:', 0.8025)
Precision:
('Decision Tree:', 0.8025)
('KNN:', 0.8025)
('Naive Bayes:', 0.8025)
Recall:
('Decision Tree:', 0.8025)
('KNN:', 0.8025)
('Naive Bayes:', 0.8025)
